spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${JDBC_DATABASE_URL}
        username: hgonnreaerhhkj
        password: C6yRaOd-wB0tVEGPO2i2bWh75m
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
    port: 8080